name: Update Volunteer Data
on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:     # Ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y iconv jq

      - name: Download and process data
        run: |
          # Скачиваем данные (с повтором при ошибке)
          for i in {1..3}; do
            curl -L -f "https://docs.google.com/spreadsheets/d/1J1GEEx5o7JiZGz60MGQw7bNxNYBJyuIVDASf-uNs_To/export?format=csv" -o data.csv && break || sleep 5
          done

          # Конвертируем кодировку и очищаем данные
          iconv -f WINDOWS-1251 -t UTF-8 data.csv > data_clean.csv
          sed -i 's/[^[:print:]\t]//g' data_clean.csv  # Удаляем непечатные символы

          # Конвертируем в JSON с обработкой ошибок
          jq -Rn '
            [inputs
             | select(length > 0)
             | gsub("\""; "") | split(",")
             | select(length >= 3)
             | {
                 "name": .[0],
                 "events": (.[1] | try tonumber catch 0),
                 "points": (.[2] | try tonumber catch 0),
                 "placr": (.[3] | try tonumber catch 0),
               }
            ]' < data_clean.csv > data.json

          # Проверяем результат
          if [ ! -s data.json ]; then
            echo "Ошибка: data.json пуст или не создан"
            exit 1
          fi

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Проверяем, есть ли изменения
          git diff --no-patch --exit-code data.json || {
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git add data.json
            git commit -m "Auto-update volunteer data $(date +'%Y-%m-%d %H:%M')"
            git push origin HEAD
          }
