name: Update Data
on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:     # Ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y iconv jq

      - name: Fetch and convert data
        run: |
          # Скачиваем CSV и исправляем кодировку
          curl -L "https://docs.google.com/spreadsheets/d/1J1GEEx5o7JiZGz60MGQw7bNxNYBJyuIVDASf-uNs_To/export?format=csv" | iconv -f WINDOWS-1251 -t UTF-8 > data.csv
          
          # Отладочная информация (можно удалить после проверки)
          echo "=== Первые 5 строк CSV ==="
          head -n 5 data.csv
          echo "========================="
          
          # Конвертируем в JSON с обработкой ошибок
          jq -Rn '
            [inputs
             | select(length > 0)
             | gsub("\""; "") | split(",")
             | {
                 "name": .[0],
                 "events": (.[1] | try tonumber catch 0),
                 "points": (.[2] | try tonumber catch 0),
                 "place": (.] | try tonumber catch 0)
               }
            ]
          ' < data.csv > data.json || echo "Ошибка при конвертации в JSON"

          # Проверяем результат
          echo "=== Содержимое JSON ==="
          cat data.json
          echo "======================="

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git diff --cached --quiet || git commit -m "Auto-update data"
          git push
