name: Update Volunteer Data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download data
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/1J1GEEx5o7JiZGz60MGQw7bNxNYBJyuIVDASf-uNs_To/export?format=csv" -o data.csv || {
            echo "::error::Не удалось скачать CSV";
            exit 1;
          }

      - name: Convert to JSON
        run: |
          # Преобразуем CSV в JSON
          jq -Rn '
            [inputs
             | select(length > 0)
             | gsub("\""; "") | split(",")
             | {
                 "name": .[0],
                 "events": (.[1] | try tonumber catch 0),
                 "points": (.[2] | try tonumber catch 0),
                 "place": (.[3] | try tonumber catch 0)
               }
            ]' < data.csv > data.json || {
              echo "::error::Ошибка преобразования CSV в JSON";
              exit 1;
            }

          # Проверяем результат
          if [ $(stat -c%s "data.json") -lt 5 ]; then
            echo "::error::Получен пустой JSON-файл";
            exit 1;
          fi

      - name: List files before commit
        run: ls -la

      - name: Force commit and push
        run: |
          # Принудительно добавляем файл
          git add -f data.json
          
          # Создаем коммит (даже если изменений нет)
          git commit -m "Force update: $(date +'%Y-%m-%d %H:%M:%S')" --allow-empty
          
          # Принудительный push с перезаписью истории
          git push --force-with-lease origin HEAD
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify push
        run: |
          echo "Проверяем наличие data.json в репозитории..."
          curl -s https://api.github.com/repos/${{ github.repository }}/contents/data.json | jq .content
