name: Update Volunteer Data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install pandas
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Download and process data
        run: |
          # Скачиваем данные с проверкой
          echo "=== Скачивание CSV ==="
          curl -v -L "https://docs.google.com/spreadsheets/d/1J1GEEx5o7JiZGz60MGQw7bNxNYBJyuIVDASf-uNs_To/export?format=csv" -o data.csv
          
          echo "=== Проверка содержимого CSV ==="
          head -n 5 data.csv
          echo "======================"
          
          # Конвертируем через Python (надежнее)
          echo "=== Конвертация в JSON ==="
          python -c "
          import pandas as pd
          import json
          
          # Читаем CSV, пропускаем пустые строки
          df = pd.read_csv('data.csv', encoding='utf-8', keep_default_na=False)
          
          # Фильтруем пустые строки
          df = df[df.iloc[:, 0].notna()]
          
          # Конвертируем в JSON
          result = df.to_dict(orient='records')
          
          # Сохраняем с красивым форматированием
          with open('data.json', 'w', encoding='utf-8') as f:
              json.dump(result, f, ensure_ascii=False, indent=2)
          "
          
          echo "=== Проверка JSON ==="
          cat data.json
          echo "===================="
          
          # Проверяем размер файла
          if [ $(stat -c%s "data.json") -lt 10 ]; then
            echo "::error::JSON файл слишком мал!"
            exit 1
          fi

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add data.json
          git status
          git commit -m "Data update: $(date +'%Y-%m-%d %H:%M')" || echo "Нет изменений для коммита"
          git push
