name: Update Volunteer Data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas

      - name: Download data
        run: |
          curl -L -f "https://docs.google.com/spreadsheets/d/e/2PACX-1vT1ZqIl-YoI4bkefOkLBYPj3QcVEsXgnnhfW65ku2gvNj65ungX5tIpzbRo9DMTMaqSlvats--5e5V_/pub?gid=0&single=true&output=csv" -o data.csv

      - name: Process data
        run: |
          python -c "
          import pandas as pd
          df = pd.read_csv('data.csv')[['ФИО','Мероприятия','Баллы','Место']]
          df.columns = ['name','events','points','place']
          df.to_json('data.json', orient='records', indent=2, force_ascii=False)
          "

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}

      - name: Commit and push
        run: |
          git add data.json
          git commit -m "Autoupdate $(date +'%Y-%m-%d %H:%M')" || exit 0
          git pull --rebase
          git push origin HEAD:main
