name: Update Volunteer Data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3
          python3 -m pip install pandas

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global --add safe.directory /github/workspace

      - name: Download and process data
        run: |
          # Скачиваем данные (3 попытки)
          for i in {1..3}; do
            curl -L -f "https://docs.google.com/spreadsheets/d/1J1GEEx5o7JiZGz60MGQw7bNxNYBJyuIVDASf-uNs_To/export?format=csv" -o data.csv && break || sleep 5
          done || { echo "::error::Не удалось скачать CSV"; exit 1; }

          # Конвертируем через Python
          python3 -c "
          import pandas as pd
          import json
          
          df = pd.read_csv('data.csv', encoding='utf-8-sig')
          df = df.dropna(how='all')
          df.to_json('data.json', orient='records', force_ascii=False, indent=2)
          "

          # Проверяем результат
          if [ $(stat -c%s "data.json") -lt 10 ]; then
            echo "::error::Получен пустой JSON-файл"
            exit 1
          fi

          echo "=== Содержимое data.json ==="
          head -n 20 data.json

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add data.json
          git status
          git commit -m "Data update: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git pull --rebase
          git push
