name: Update Volunteer Data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          python3 -m pip install pandas

      - name: Download and process data
        run: |
          # Скачивание данных (3 попытки)
          for i in {1..3}; do
            curl -L -f "https://docs.google.com/spreadsheets/d/e/2PACX-1vT1ZqIl-YoI4bkefOkLBYPj3QcVEsXgnnhfW65ku2gvNj65ungX5tIpzbRo9DMTMaqSlvats--5e5V_/pub?gid=0&single=true&output=csv" -o data.csv && break || sleep 5
          done || { echo "::error::Не удалось скачать CSV"; exit 1; }

          # Конвертация в JSON
          python3 -c "
          import pandas as pd
          df = pd.read_csv('data.csv', encoding='utf-8-sig')
          df = df[['ФИО', 'Мероприятия', 'Баллы', 'Место']]
          df.columns = ['name', 'events', 'points', 'place']
          df.to_json('data.json', orient='records', force_ascii=False, indent=2)
          "


      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Настройка Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n "x-access-token:${{ secrets.GITHUB_TOKEN }}" | base64)"

          # Коммит и пуш
          git add data.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automatic data update: $(date +'%Y-%m-%d %H:%M')"
            git pull --rebase
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
