name: Update Volunteer Data
on:
  schedule:
    - cron: '0 * * * *'  # Запускать каждый час
  workflow_dispatch:     # Разрешить ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          python3 -m pip install pandas

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Download and process data
        run: |
          # Скачиваем данные с 3 попытками
          for i in {1..3}; do
            curl -L -f "https://docs.google.com/spreadsheets/d/e/2PACX-1vT1ZqIl-YoI4bkefOkLBYPj3QcVEsXgnnhfW65ku2gvNj65ungX5tIpzbRo9DMTMaqSlvats--5e5V_/pub?gid=0&single=true&output=csv" -o data.csv && break || sleep 5
          done || { echo "::error::Не удалось скачать CSV"; exit 1; }

          # Конвертируем CSV в JSON
          python3 -c "
          import pandas as pd
          import json
          
          df = pd.read_csv('data.csv', encoding='utf-8-sig')
          df = df.dropna(how='all')
          df.to_json('data.json', orient='records', force_ascii=False, indent=2)
          "

          # Проверяем результат
          if [ $(stat -c%s "data.json") -lt 10 ]; then
            echo "::error::Получен пустой JSON-файл"
            exit 1
          fi

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Добавляем файл и делаем коммит
          git add data.json
          git commit -m "Data update: $(date +'%Y-%m-%d %H:%M')" || exit 0
          
          # Если есть изменения, пушим их
          if [ -n "$(git status --porcelain)" ]; then
            git pull --rebase
            git push
          else
            echo "Нет изменений для коммита"
          fi
