name: Update Volunteer Data
on:
  schedule:
    - cron: '0 * * * *'  # Каждый час
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas

      - name: Download data
        run: |
          curl -L -f "https://docs.google.com/spreadsheets/d/e/2PACX-1vT1ZqIl-YoI4bkefOkLBYPj3QcVEsXgnnhfW65ku2gvNj65ungX5tIpzbRo9DMTMaqSlvats--5e5V_/pub?gid=0&single=true&output=csv" -o data.csv
          echo "Проверка первых строк CSV:"
          head -n 3 data.csv

      - name: Convert to JSON
        run: |
          python -c "
          import pandas as pd
          import json
          
          # Читаем CSV файл
          df = pd.read_csv('data.csv', encoding='utf-8-sig')
          
          # Выводим список колонок для отладки
          print('Доступные колонки:', df.columns.tolist())
          
          # Переименовываем колонки (если нужно)
          df = df.rename(columns={
            'ФИО': 'name',
            'Добрые дела': 'events',
            'Баллы': 'points',
            'Место': 'place'
          })
          
          # Выбираем нужные колонки
          df = df[['name', 'events', 'points', 'place']]
          
          # Сохраняем в JSON
          df.to_json('data.json', orient='records', force_ascii=False, indent=2)
          print('Данные успешно преобразованы в JSON')
          "

      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data.json
          git commit -m "Autoupdate $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
