name: Update Data
on:
  schedule:
    - cron: '0 * * * *'  # Каждый час

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch new data
        run: |
          curl "https://ваш-api-для-данных" > data.json
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@github.com"
          git add data.json
          git commit -m "Auto-update data"
          git push
